package com.jkjk.GameWorld;

enum TutorialStep {
	NONE,
	CHARACTER_INTRO,
	HUD_OVERVIEW,
	ABILITY_OVERVIEW,
	WAITING_FOR_WEAPON_PICKUP,
	WAITING_FOR_WEAPON_USE,
	WAITING_FOR_ITEM_PICKUP,
	WAITING_FOR_ITEM_USE,
	WAITING_FOR_WEAPON_PARTS,
	GHOST_INTRO,
	COMPLETE,
	MAP_OVERVIEW
}
